class DataCharacter {
  String name;
  String element;
  String nation;
  String gender;
  String weapon;
  String description;
  String image_character;
  String background_card;
  int rarity;

  DataCharacter({
    required this.name,
    required this.element,
    required this.nation,
    required this.gender,
    required this.weapon,
    required this.description,
    required this.image_character,
    required this.background_card,
    required this.rarity,
  });
}

var characterList = [
  DataCharacter(
    name: "Venti",
    element: "Anemo",
    nation: "Mondstadt",
    gender: "Male",
    weapon: "Bow",
    description: "Venti is a playable Anemo character in Genshin Impact. He is a free-spirited, wine-loving bard of Mondstadt, belying his identity as Barbatos, the Anemo Archon.",
    image_character: "https://static.wikia.nocookie.net/gensin-impact/images/2/2d/Character_Venti_Full_Wish.png/revision/latest?cb=20220507131746",
    background_card: "images/mondstadt.webp",
    rarity: 5,
  ),
  DataCharacter(
    name: "Zhongli",
    element: "Geo",
    nation: "Liyue",
    gender: "Male",
    weapon: "Polearm",
    description: "Zhongli is a playable Geo character in Genshin Impact. A consultant of the Wangsheng Funeral Parlor, he is later revealed to be the Geo Archon, Morax, who has decided to experience the world from the perspective of a mortal.",
    image_character: "https://static.wikia.nocookie.net/gensin-impact/images/c/c4/Character_Zhongli_Full_Wish.png/revision/latest?cb=20220507161902",
    background_card: "images/liyue.webp",
    rarity: 5,
  ),
  DataCharacter(
    name: "Raiden Shogun",
    element: "Electro",
    nation: "Inazuma",
    gender: "Female",
    weapon: "Polearm",
    description: "The Raiden Shogun is a playable Electro character in Genshin Impact. The Raiden Shogun is comprised of two beings in one body: Ei, the current Electro Archon of Inazuma; and the Shogun, the puppet created by Ei to act as the ruler of Inazuma in her stead.",
    image_character: "https://static.wikia.nocookie.net/gensin-impact/images/a/a3/Character_Raiden_Shogun_Full_Wish.png/revision/latest?cb=20220507154003",
    background_card: "images/inazuma.webp",
    rarity: 5,
  ),
  DataCharacter(
    name: "Nahida",
    element: "Dendro",
    nation: "Sumeru",
    gender: "Female",
    weapon: "Catalyst",
    description: "Nahida is a playable Dendro character in Genshin Impact. As Lesser Lord Kusanali, she strives to have a stronger presence in Sumeru now that she has been freed from her extensive confinement in the Sanctuary of Surasthana.",
    image_character: "https://static.wikia.nocookie.net/gensin-impact/images/d/dd/Character_Nahida_Full_Wish.png/revision/latest?cb=20221102032214",
    background_card: "images/sumeru.webp",
    rarity: 5,
  ),
  DataCharacter(
    name: "Furina",
    element: "Hydro",
    nation: "Fontaine",
    gender: "Female",
    weapon: "Sword",
    description: "Furina de Fontaine is a playable Hydro character in Genshin Impact who can alternate between Pneuma and Ousia alignments. Introduced as the flamboyant and overconfident Hydro Archon, Furina theatrics are eventually revealed to be a public persona, which she later discards in favor of living a relatively humbler life as an actress and artistic consultant.",
    image_character: "https://static.wikia.nocookie.net/gensin-impact/images/9/94/Character_Furina_Full_Wish.png/revision/latest?cb=20231108064320",
    background_card: "images/fontaine.webp",
    rarity: 5,
  ),
  DataCharacter(
    name: "Xilonen",
    element: "Geo",
    nation: "Natlan",
    gender: "Female",
    weapon: "Sword",
    description: "Xilonen is a playable Geo character in Genshin Impact. \n A Name Engraver for the Children of Echoes bearing her own Ancient Name of 'Baraka', Xilonen is often found enjoying her leisure time with naps in the sun but at the forge, her craftsmanship is next to none.",
    image_character: "https://static.wikia.nocookie.net/gensin-impact/images/f/f5/Character_Xilonen_Full_Wish.png/revision/latest/scale-to-width-down/1000?cb=20241009044950",
    background_card: "images/natlan.webp",
    rarity: 5,
  ),
  DataCharacter(
    name: "Bennett",
    element: "Pyro",
    nation: "Mondstadt",
    gender: "Male",
    weapon: "Sword",
    description: "Bennett is a playable Pyro character in Genshin Impact. An orphan discovered by an elderly adventurer as a baby, Bennett was raised in Mondstadt Adventurers Guild. He is the one and only member of 'Benny's Adventure Team,' as everyone else left the team after experiencing the constant misfortune that follows him.",
    image_character: "https://static.wikia.nocookie.net/gensin-impact/images/2/27/Character_Bennett_Full_Wish.png/revision/latest?cb=20220507132108",
    background_card: "images/mondstadt.webp",
    rarity: 4,
  ),
  DataCharacter(
    name: "Arlecchino",
    element: "Pyro",
    nation: "Fontaine",
    gender: "Female",
    weapon: "Polearm",
    description: "Arlecchino, also known by her codename 'The Knave,' is a playable Pyro character in Genshin Impact. She is the Fourth of the Eleven Fatui Harbingers and the current head of the House of the Hearth. She is addressed as 'Father' by members of the House, who she calls her 'children.'",
    image_character: "https://static.wikia.nocookie.net/gensin-impact/images/f/f8/Character_Arlecchino_Full_Wish.png/revision/latest?cb=20240424142733",
    background_card: "images/fontaine.webp",
    rarity: 5,
  ),
  DataCharacter(
    name: "Eula",
    element: "Cryo",
    nation: "Mondstadt",
    gender: "Female",
    weapon: "Claymore",
    description: "Eula Lawrence is a playable Cryo character in Genshin Impact. Although a descendant of the infamous and tyrannical Lawrence Clan, Eula severed her ties with the clan and became the captain of the Reconnaissance Company with the Knights of Favonius.",
    image_character: "https://static.wikia.nocookie.net/gensin-impact/images/6/6d/Character_Eula_Full_Wish.png/revision/latest?cb=20240525000817",
    background_card: "images/mondstadt.webp",
    rarity: 5,
  ),
  DataCharacter(
    name: "Hu Tao",
    element: "Pyro",
    nation: "Liyue",
    gender: "Female",
    weapon: "Polearm",
    description: "Hu Tao antics and eccentricity belies her role as the 77th Director of the Wangsheng Funeral Parlor and her talent as a poet. Nevertheless, she treats the parlor operations with utmost importance, and holds funeral ceremonies with the highest dignity and solemnity.",
    image_character: "https://static.wikia.nocookie.net/gensin-impact/images/5/59/Character_Hu_Tao_Full_Wish.png/revision/latest/scale-to-width-down/1000?cb=20220507160922",
    background_card: "images/liyue.webp",
    rarity: 5,
  ),
  DataCharacter(
    name: "Kadehara Kazuha",
    element: "Anemo",
    nation: "Inazuma",
    gender: "Male",
    weapon: "Sword",
    description: "Kaedehara Kazuha is a playable Anemo character in Genshin Impact. A wandering samurai of the once-famed Kaedehara Clan with an ability to read the sounds of nature, Kazuha is a temporary crewmember of The Crux. Despite being burdened by the many happenings of his past, Kazuha still maintains an easygoing disposition.",
    image_character: "https://static.wikia.nocookie.net/gensin-impact/images/5/57/Character_Kaedehara_Kazuha_Full_Wish.png/revision/latest?cb=20220507131548",
    background_card: "images/inazuma.webp",
    rarity: 5,
  ),
  DataCharacter(
    name: "Kamisato Ayaka",
    element: "Cryo",
    nation: "Inazuma",
    gender: "Female",
    weapon: "Sword",
    description: "Kamisato Ayaka is a playable Cryo character in Genshin Impact. She is in charge of the internal and external affairs of the Kamisato Clan and is the younger sister of Kamisato Ayato. Beautiful, dignified, and noble, Ayaka has earned the title Shirasagi Himegimi and is considered a model of perfection in Inazuma.",
    image_character: "https://static.wikia.nocookie.net/gensin-impact/images/d/d0/Character_Kamisato_Ayaka_Full_Wish.png/revision/latest?cb=20221014024207",
    background_card: "images/inazuma.webp",
    rarity: 5,
  ),
  DataCharacter(
    name: "Jean",
    element: "Anemo",
    nation: "Mondstadt",
    gender: "Female",
    weapon: "Sword",
    description: "Jean is a playable Anemo character in Genshin Impact. She serves as the Acting Grand Master of the Knights of Favonius, although the position weighs heavily on her. She takes her duties and role as a leader seriously, which has made her well-loved and trusted by the people of Mondstadt.",
    image_character: "https://static.wikia.nocookie.net/gensin-impact/images/d/d6/Character_Jean_Full_Wish.png/revision/latest/scale-to-width-down/1000?cb=20221014022733",
    background_card: "images/mondstadt.webp",
    rarity: 5,
  ),
  DataCharacter(
    name: "Neuvillette",
    element: "Hydro",
    nation: "Fontaine",
    gender: "Male",
    weapon: "Catalyst",
    description: "Neuvillette is a playable Pneuma-aligned Hydro character in Genshin Impact. Neuvillette is the Iudex of Fontaine, and the leader of the Marechaussee Phantom. While Neuvillette upholds the rules of the court with utmost reverence, he is quite aloof when dealing with human emotions and often distances himself from the public eye. Despite his human appearance, he is actually the Hydro Dragon Sovereign.",
    image_character: "https://static.wikia.nocookie.net/gensin-impact/images/5/5e/Character_Neuvillette_Full_Wish.png/revision/latest/scale-to-width-down/1000?cb=20240119144458",
    background_card: "images/fontaine.webp",
    rarity: 5,
  ),
  DataCharacter(
    name: "Mualani",
    element: "Hydro",
    nation: "Natlan",
    gender: "Female",
    weapon: "Catalyst",
    description: "Mualani is a playable Hydro character in Genshin Impact. Being a guide, a surfer, and a watersports shop owner for the People of the Springs who bears the Ancient Name 'Umoja', Mualani is an active and sweet person, and she is always able to satisfy her clients.",
    image_character: "https://static.wikia.nocookie.net/gensin-impact/images/a/a4/Character_Mualani_Full_Wish.png/revision/latest/scale-to-width-down/1000?cb=20240913071517",
    background_card: "images/natlan.webp",
    rarity: 5,
  ),
  DataCharacter(
    name: "Kinich",
    element: "Dendro",
    nation: "Natlan",
    gender: "Male",
    weapon: "Claymore",
    description: "Kinich is a playable Dendro character in Genshin Impact. A Saurian Hunter from the Scions of the Canopy with the Ancient Name 'Malipo', Kinich is a taciturn individual who has a knack for calculating the price of any request — even wetwork — due to his utilitarian philosophy.",
    image_character: "https://static.wikia.nocookie.net/gensin-impact/images/9/95/Character_Kinich_Full_Wish.png/revision/latest/scale-to-width-down/1000?cb=20240919141401",
    background_card: "images/natlan.webp",
    rarity: 5,
  ),
];
